### PR TITLE
fix: add focus to itemobtain

### PR DESCRIPTION
**Pull request by alisonrag**
this pull fixes: #309 

after:
image

### CODE REVIEW

**Comment by alisonrag** [comment]
client:
image

**Comment by MrAntares** [comment]
I am not sure this is a good approach. The label should never have focus, this is merely a z-index issue. Changing focus on item obtain might mess up other UI functionality, like changing focus when typing, or changing focus from a window that should block other UIs, like storage. Did you test these scenarios?

**Comment by waken22** [comment]
> I am not sure this is a good approach. The label should never have focus, this is merely a z-index issue. Changing focus on item obtain might mess up other UI functionality, like changing focus when typing, or changing focus from a window that should block other UIs, like storage. Did you test these scenarios?

That's the reason i didn't merged yet :)
Didn't have the time to test this PR.

**Comment by alisonrag** [comment]
@MrAntares updated
image

**Pull request merged**
