### PR TITLE
AP System

### PR DESCRIPTION
**Pull request by Samuel23**
Adding the AP System for 4th job classes

### CODE REVIEW

**Comment by Samuel23** [comment]
Changed into draft because BasicInfo for the newer clients also checks for job class, as non 4th job class will show the basicinfov4 while 4th jobs will show the basicinfov5

**Comment by Samuel23** [comment]
Done adding support to UI changing depending on Job in character selection and during job change and fixed some bugs

**Comment by MrAntares** [comment]
I think the version handling needs some improvement.
I'd prefer having the 4th class ui selection handled by the ui selector itslef instead of again having the dates in the core code. The UI ver list already has the "default", "pre-re" and "re" versions of the UIs, it could also have a "4th_class" category that defines the UI versions that is selected for classes with 4th class+ AP system and the talent/trait points. Eventually there would be multiple UI versions even in this new category, so it would be best to keep all these in one place.
The function that tells which class is 4th class could be in DBManager. We already need something similar, that tells the base class, is rebirth class, is 3rd class, so having a func that tells if is 4th class would be pretty much in line with these needs, and then the UI selector could query this func.

**Comment by Samuel23** [comment]
Hmmm, i will look into this but as of now, only the BasicInfo has the need for this job class dependent UI

the WinStats (which I am currently doing, is not job dependent - what the client version provides is used for all job classes, and it seems true to all current UIs we have)

Though I get the need for the class selection in DBManager (then use it as a basis for the UI selection)

**Comment by MrAntares** [comment]
Hmm I thought the new stats are only used for the 4th+classes. So they are visible even before that?

**Comment by Samuel23** [comment]
Yes trait status is only applicable for 4th Class but they are still visible with whatever job you have, you just can't add traits because trait points will be 0 and trait requirements will not be updated for non 4th job Class

Image from client for non 4th Job Class: (excuse the over-stats XD)
image

image

as of now, only the AP bar and BasicInfo is dependent on 4th Job Class

updated this pull request as well

**Pull request merged**
