### PR TITLE
Merging from MrUnzO work

### PR DESCRIPTION
**Pull request by waken22**
There's a lot of his work here, some work is already done other not yet.

It includes : (wip)

    fix on animation speed

This atm is a WiP, don't hurry up to merge!

### CODE REVIEW

**Comment by alisonrag** [comment]
image

need to be carefull, maybe implement these changes one by one in separated pulls

**Comment by waken22** [comment]
> image
> 
> need to be carefull, maybe implement these changes one by one in separated pulls

Don't worry, this is a WiP, i can revert all of those commits.

**Comment by kontownik** [comment]
Hey guys @waken22 @alisonrag @MrAntares  so what is the decision? we will split into smaller PR's I think?

**Comment by MrAntares** [comment]
I think most of these are now obsolete. We can merge smaller things if they are useful or copy pasta parts, but I advise against merging larger things

**Comment by alisonrag** [comment]
most of it is already implemented, i think we just left the nw,js feature

**Pull request closed without merging**
