### PR TITLE
fix: show aura for dead entities

### PR DESCRIPTION
**Pull request by gulfaraz**
- supposedly in the official clients aura doesn't get remove when a character dies (at least tested in a 2018 client)

### CODE REVIEW

**Comment by MrAntares** [comment]
Won't this leave an aura for dead mobs on the map?

**Comment by MrAntares** [comment]
Some mobs have an aura i think

**Comment by gulfaraz** [comment]
@MrAntares you're right, I'll make a new PR

**Comment by neico** [comment]
You can probably leave the `isDead` method, someone else might have a use for it for something else.

**Pull request merged**
